name: CD - Continous Delivery (DEMOS)

on:
  push:
    branches: [ main ]

env:
  GH_GLOBAL_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN_GLOBAL: ${{ secrets.VERCEL_TOKEN_GLOBAL }}
  VERCEL_PROJECT_ID__DEMO_FLUTTER: ${{ secrets.VERCEL_PROJECT_ID__DEMO_FLUTTER }}

jobs:
  release_demo_flutterweb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.3'
    - name: "Start: Release Web"
      env: 
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID__DEMO_FLUTTER }}
      run: |
        yarn install
        yarn deploy:flutterweb:demo
