name: Release
on:
  push:
    branches:
      - main

env:
  GIT_AUTHOR_NAME: "@bumper-bot"
  GITHUB_TOKEN: ${{ secrets.GH_MASTER_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GH_MASTER_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Install dependencies
        run: yarn install
      - name: Release NPM Registry & Flutter Pub
        run: |
          echo 'Run Flutter CI Steps'
          echo $GITHUB_TOKEN
          yarn build
          yarn release
